server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  elasticsearch:
    rest:
      uris: http://192.168.64.130:9200
  rabbitmq:
    virtual-host: /jiaxin
    host: 192.168.64.130
    username: jiaxin
    password: jiaxin